import os
#os.system("espeak-ng install_h_t_t_p_d")
os.system("yum install httpd")
#os.system("espeak-ng opening_h_t_m_l_directory")
os.system("cd /var/www/html/gedit myweb.html")
#os.system("espeak-ng start__h_t_t_p_d_service")
os.system("systemctl start httpd")
os.system("ifconfig enp0s3")
#os.system("espeak-ng please_copy_the_ip_address")
#os.system("espeak-ng opening_firefox")
os.system("firefox")
